---
  - name: Update packages
    apt:
      update_cache: true
      upgrade: yes

  - name: Install dependencies
    package:
      name: "{{ item }}"
      state: latest
    loop:
      - firewalld
      - apt-transport-https

  - name: Create Java repo
    shell: |
      mkdir -p /etc/apt/keyrings
      wget -O - https://packages.adoptium.net/artifactory/api/gpg/key/public | tee /etc/apt/keyrings/adoptium.asc
      echo "deb [signed-by=/etc/apt/keyrings/adoptium.asc] https://packages.adoptium.net/artifactory/deb $(awk -F= '/^VERSION_CODENAME/{print$2}' /etc/os-release) main" | tee /etc/apt/sources.list.d/adoptium.list

  - name: Update packages
    apt:
      update_cache: true

  - name: Install Java
    package:
      name: temurin-17-jdk
      state: latest

  - name: Change Java version to 17
    alternatives:
      name: java
      path: /usr/lib/jvm/temurin-17-jdk-amd64/bin/java

