--- 
  - name: Install PostgreSQL Repository
    shell: |
      dnf install -y https://download.postgresql.org/pub/repos/yum/reporpms/EL-8-x86_64/pgdg-redhat-repo-latest.noarch.rpm
      dnf module disable postgresql -y

  - name: Install PostgreSQL
    yum: 
      name: "{{ item }}"
      state: present
    loop:
      - postgresql14-server
      - postgresql14

  - name: Run postgresql
    shell: |
      /usr/pgsql-14/bin/postgresql-14-setup initdb
      systemctl enable --now postgresql-14
      systemctl start postgresql-14

